apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend-deployment
  labels:
    app: devops-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
        - name: devops-backend
          image: srisaiganesh/devops-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
