apiVersion: v1
kind: Service
metadata:
  name: devops-backend-service
spec:
  selector:
    app: devops-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30040
  type: NodePort
