apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend-deployment
  labels:
    app: devops-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      containers:
        - name: devops-frontend
          image: badhriamaraboina/devops-frontend2-dev:latest
          ports:
            - containerPort: 5173
