global:
  scrape_interval: 4s

scrape_configs:
  - job_name: "mern-backend"   # Name of your backend metrics job
    metrics_path: "/metrics"   # Prometheus will scrape this endpoint
    static_configs:
      - targets: ["backend:4000"]  # Backend service name in Docker
